import { Product } from "@/types/product";
const shopData: Product[] = [
  {
    name_en: "Havit HV-G69 USB Gamepad",
    name_ar: "هافيت HV-G69 USB جيمباد",
    title: "Havit HV-G69 USB Gamepad",
    reviews: 15,
    price: 59.0,
    offer_price: 29.0,
    discountedPrice: 29.0,
    id: 1,
    image_url: "/images/products/product-1-sm-1.png",
    stock_quantity: 10,
    description_en: "High-quality USB gamepad for gaming enthusiasts",
    description_ar: "جيمباد USB عالي الجودة لعشاق الألعاب",
    imgs: {
      thumbnails: [
        "/images/products/product-1-sm-1.png",
        "/images/products/product-1-sm-2.png",
      ],
      previews: [
        "/images/products/product-1-bg-1.png",
        "/images/products/product-1-bg-2.png",
      ],
    },
  },
  {
    name_en: "iPhone 14 Plus , 6/128GB",
    name_ar: "آيفون 14 بلس، 6/128 جيجابايت",
    title: "iPhone 14 Plus , 6/128GB",
    reviews: 5,
    price: 899.0,
    offer_price: 99.0,
    discountedPrice: 99.0,
    id: 2,
    image_url: "/images/products/product-2-sm-1.png",
    stock_quantity: 5,
    description_en: "Latest iPhone with advanced features and performance",
    description_ar: "أحدث آيفون مع ميزات متقدمة وأداء عالي",
    imgs: {
      thumbnails: [
        "/images/products/product-2-sm-1.png",
        "/images/products/product-2-sm-2.png",
      ],
      previews: [
        "/images/products/product-2-bg-1.png",
        "/images/products/product-2-bg-2.png",
      ],
    },
  },
  {
    name_en: "Apple iMac M1 24-inch 2021",
    name_ar: "آبل آي ماك M1 24 بوصة 2021",
    title: "Apple iMac M1 24-inch 2021",
    reviews: 5,
    price: 59.0,
    offer_price: 29.0,
    discountedPrice: 29.0,
    id: 3,
    image_url: "/images/products/product-3-sm-1.png",
    stock_quantity: 8,
    description_en: "Powerful all-in-one desktop with M1 chip",
    description_ar: "كمبيوتر مكتبي شامل قوي مع شريحة M1",
    imgs: {
      thumbnails: [
        "/images/products/product-3-sm-1.png",
        "/images/products/product-3-sm-2.png",
      ],
      previews: [
        "/images/products/product-3-bg-1.png",
        "/images/products/product-3-bg-2.png",
      ],
    },
  },
  {
    name_en: "MacBook Air M1 chip, 8/256GB",
    name_ar: "ماك بوك إير شريحة M1، 8/256 جيجابايت",
    title: "MacBook Air M1 chip, 8/256GB",
    reviews: 6,
    price: 59.0,
    offer_price: 29.0,
    discountedPrice: 29.0,
    id: 4,
    image_url: "/images/products/product-4-sm-1.png",
    stock_quantity: 12,
    description_en: "Ultra-portable laptop with exceptional performance",
    description_ar: "لابتوب فائق المحمولية مع أداء استثنائي",
    imgs: {
      thumbnails: [
        "/images/products/product-4-sm-1.png",
        "/images/products/product-4-sm-2.png",
      ],
      previews: [
        "/images/products/product-4-bg-1.png",
        "/images/products/product-4-bg-2.png",
      ],
    },
  },
  {
    name_en: "Apple Watch Ultra",
    name_ar: "آبل ووتش ألترا",
    title: "Apple Watch Ultra",
    reviews: 3,
    price: 99.0,
    offer_price: 29.0,
    discountedPrice: 29.0,
    id: 5,
    image_url: "/images/products/product-5-sm-1.png",
    stock_quantity: 15,
    description_en: "Premium smartwatch for outdoor adventures",
    description_ar: "ساعة ذكية فاخرة للمغامرات الخارجية",
    imgs: {
      thumbnails: [
        "/images/products/product-5-sm-1.png",
        "/images/products/product-5-sm-2.png",
      ],
      previews: [
        "/images/products/product-5-bg-1.png",
        "/images/products/product-5-bg-2.png",
      ],
    },
  },
  {
    name_en: "Logitech MX Master 3 Mouse",
    name_ar: "فأرة لوجيتك MX ماستر 3",
    title: "Logitech MX Master 3 Mouse",
    reviews: 15,
    price: 59.0,
    offer_price: 29.0,
    discountedPrice: 29.0,
    id: 6,
    image_url: "/images/products/product-6-sm-1.png",
    stock_quantity: 20,
    description_en: "Advanced wireless mouse for productivity",
    description_ar: "فأرة لاسلكية متقدمة للإنتاجية",
    imgs: {
      thumbnails: [
        "/images/products/product-6-sm-1.png",
        "/images/products/product-6-sm-2.png",
      ],
      previews: [
        "/images/products/product-6-bg-1.png",
        "/images/products/product-6-bg-2.png",
      ],
    },
  },
  {
    name_en: "Apple iPad Air 5th Gen - 64GB",
    name_ar: "آبل آيباد إير الجيل الخامس - 64 جيجابايت",
    title: "Apple iPad Air 5th Gen - 64GB",
    reviews: 15,
    price: 59.0,
    offer_price: 29.0,
    discountedPrice: 29.0,
    id: 7,
    image_url: "/images/products/product-7-sm-1.png",
    stock_quantity: 7,
    description_en: "Versatile tablet for work and entertainment",
    description_ar: "تابلت متعدد الاستخدامات للعمل والترفيه",
    imgs: {
      thumbnails: [
        "/images/products/product-7-sm-1.png",
        "/images/products/product-7-sm-2.png",
      ],
      previews: [
        "/images/products/product-7-bg-1.png",
        "/images/products/product-7-bg-2.png",
      ],
    },
  },
  {
    name_en: "Asus RT Dual Band Router",
    name_ar: "راوتر آسوس RT ثنائي النطاق",
    title: "Asus RT Dual Band Router",
    reviews: 15,
    price: 59.0,
    offer_price: 29.0,
    discountedPrice: 29.0,
    id: 8,
    image_url: "/images/products/product-8-sm-1.png",
    stock_quantity: 25,
    description_en: "High-speed dual-band wireless router",
    description_ar: "راوتر لاسلكي ثنائي النطاق عالي السرعة",
    imgs: {
      thumbnails: [
        "/images/products/product-8-sm-1.png",
        "/images/products/product-8-sm-2.png",
      ],
      previews: [
        "/images/products/product-8-bg-1.png",
        "/images/products/product-8-bg-2.png",
      ],
    },
  },
];

export default shopData;
