import { BlogData } from "@/types/blogItem";

export const blogData: BlogData[] = [
  {
    id: "1",
    title_ar: "ما هي المعلومات المطلوبة للشحن؟",
    title_en: "What information is needed for shipping?",
    content_ar: "محتوى المقال باللغة العربية...",
    content_en: "Article content in English...",
    user_id: null,
    images: ["/images/blog/blog-01.jpg"],
    created_at: "2022-03-27T00:00:00Z",
    yt_code: null,
    author: "Admin",
  },
  {
    id: "2",
    title_ar: "كيف تختار اللابتوب المناسب لاحتياجاتك؟",
    title_en: "How to choose the right laptop for your needs",
    content_ar: "محتوى المقال باللغة العربية...",
    content_en: "Article content in English...",
    user_id: null,
    images: ["/images/blog/blog-02.jpg"],
    created_at: "2022-03-25T00:00:00Z",
    yt_code: null,
    author: "Admin",
  },
  {
    id: "3",
    title_ar: "أفضل إكسسوارات الألعاب لعام 2022",
    title_en: "Best gaming accessories for 2022",
    content_ar: "محتوى المقال باللغة العربية...",
    content_en: "Article content in English...",
    user_id: null,
    images: ["/images/blog/blog-03.jpg"],
    created_at: "2022-03-23T00:00:00Z",
    yt_code: null,
    author: "Admin",
  },
  {
    id: "4",
    title_ar: "سطح المكتب مقابل اللابتوب: أيهما أفضل؟",
    title_en: "Desktop vs Laptop: Which is better?",
    content_ar: "محتوى المقال باللغة العربية...",
    content_en: "Article content in English...",
    user_id: null,
    images: ["/images/blog/blog-04.jpg"],
    created_at: "2022-03-21T00:00:00Z",
    yt_code: null,
    author: "Admin",
  },
  {
    id: "5",
    title_ar: "أفضل 10 شاشات للإنتاجية",
    title_en: "Top 10 monitors for productivity",
    content_ar: "محتوى المقال باللغة العربية...",
    content_en: "Article content in English...",
    user_id: null,
    images: ["/images/blog/blog-05.jpg"],
    created_at: "2022-03-19T00:00:00Z",
    yt_code: null,
    author: "Admin",
  },
  {
    id: "6",
    title_ar: "اللاسلكي مقابل السلكي: النقاش الأبدي",
    title_en: "Wireless vs Wired: The eternal debate",
    content_ar: "محتوى المقال باللغة العربية...",
    content_en: "Article content in English...",
    user_id: null,
    images: ["/images/blog/blog-06.jpg"],
    created_at: "2022-03-17T00:00:00Z",
    yt_code: null,
    author: "Admin",
  },
];

export default blogData;
